apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/token-auth-gcp: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    operators.operatorframework.io/operator-type: non-standalone
  name: heat-operator.v0.0.1
  namespace: openstack
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HeatAPI is the Schema for the heatapis API
      displayName: Heat API
      kind: HeatAPI
      name: heatapis.heat.openstack.org
      version: v1beta1
    - description: HeatCfnAPI is the Schema for the heatcfnapis API
      displayName: Heat Cfn API
      kind: HeatCfnAPI
      name: heatcfnapis.heat.openstack.org
      version: v1beta1
    - description: HeatEngine is the Schema for the heatengines API
      displayName: Heat Engine
      kind: HeatEngine
      name: heatengines.heat.openstack.org
      version: v1beta1
    - description: Heat is the Schema for the heats API
      displayName: Heat
      kind: Heat
      name: heats.heat.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: heatAPI.tls
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: heatCfnAPI.tls
      version: v1beta1
  description: Heat Operator
  displayName: Heat Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Orchestration
  - Heat
  links:
  - name: Heat Operator
    url: https://github.com/openstack-k8s-operators/heat-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
